[package]
name = "conflux"
version = "2.3.0"
authors = ["Conflux Foundation"]
edition = "2021"

[dependencies]
ledger_device_sdk = "1.35.1"
k256 = { version = "0.13.4", default-features = false, features = ["ecdsa"] }
bigdecimal = { version = "0.4.10", default-features = false }
ledger-rust-eip712 = { git = "https://github.com/Conflux-Chain/ledger-rust-eip712.git", rev = "6e12c3f", default-features = false }
alloy-primitives = { git = "https://github.com/Conflux-Chain/alloy-rs-core.git", rev = "bbbfea7", default-features = false, features = ["rlp"] }
alloy-rlp = { git = "https://github.com/Conflux-Chain/rlp.git", rev = "0082477", default-features = false, features = ["derive"] }

[profile.release]
opt-level = 'z'
lto = true

[features]
default = ["ledger_device_sdk/nano_nbgl"]
debug = ["ledger_device_sdk/debug"]

[package.metadata.ledger]
curve = ["secp256k1"]
flags = "0"
path = ["44'/503'"]
name = "Conflux"

[package.metadata.ledger.nanox]
icon = "icons/cfx_14.gif"

[package.metadata.ledger.nanosplus]
icon = "icons/cfx_14.gif"

[package.metadata.ledger.stax]
icon = "icons/cfx_32.gif"

[package.metadata.ledger.flex]
icon = "icons/cfx_40.gif"

[package.metadata.ledger.apex_p]
icon = "icons/cfx_32.png"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("apex_p", "stax", "flex", "nanos", "nanox", "nanosplus"))'] }